apiVersion: apps/v1
kind: Deployment
metadata:
  name: schemaapi-deployment
  namespace: skema
  labels:
    app: schemaapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schemaapi
  template:
    metadata:
      labels:
        app: schemaapi
    spec:
      containers:
        - name: schemaapi-app
          image: homepi:14000/schemaapi:{{BUILD_NUMBER}}
          ports:
            - name: web
              containerPort: 80
          envFrom:
            - secretRef:
                name: pushover
            - configMapRef:
                name: schemaurls
---
apiVersion: v1
kind: Service
metadata:
  name: schemaapi-service
  namespace: skema
spec:
  selector:
    app: schemaapi
  ports:
    - name: external
      protocol: TCP
      port: 80
      targetPort: web
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: schemaapi-ingress
  namespace: skema
spec:
  # entryPoints:
  #   - web
  routes:
    - match: Host(`homepi`) && PathPrefix(`/schemaapi`)
      kind: Rule
      services:
        - name: schemaapi-service
          port: 80
      middlewares:
        - name: schemaapi-middleware
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: schemaapi-middleware
  namespace: skema
spec:
  stripPrefix:
    prefixes:
      - /schemaapi
